### ISSUE TITLE
Gradle Sync failing when importing project

### ISSUE THREAD

**Issue by huljar** [DictionaryForMIDs/Android#1]
Hello,

I cloned the repo and tried to import it in Android Studio 2.2.3. However, the Gradle Sync process failed with the following error in the build.gradle file:

```
Error:(58, 0) Could not get unknown property 'releaseStoreFile' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
```

I'm using the latest Android Studio and latest Grade version on a Debian machine.

**Comment by a-xin** [comment]
Hey, I just added a `gradle.properties.TEMPLATE` file to the project - just rename the file to `gradle.properties` and try again.

**Comment by huljar** [comment]
Thanks, this solves the variables not being found. However, now the Gradle Sync fails with `Error: Configuration with name 'default' not found.`

**Comment by a-xin** [comment]
As discussed, I created a root projected and added setup instructions there:
https://github.com/DictionaryForMIDs/Root#setup

Please report back here if you are still facing any issues or if the setup instructions are unclear and missing information.
